# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Guangcan Mai
tagline:             'Working by heart'
description:         'Be the fire and wish for the wind'
# url:                 http://www.maiguangcan.cn
baseurl:             ''
gems:                 [jekyll-paginate]
paginate_path: "page:num"
paginate:            5

# About/contact
author:
  name:              Makchan Guangcan Mai
  url:               http://www.comp.hkbu.edu.hk/~csgcmai
  email:             csgcmai@life.hkbu.edu.hk

# Custom vars
version:             1.0.0
