# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Guangcan Mai
tagline:             'Working by heart'
description:         'To be a better man'
url:                 http://www.maiguangcan.cn
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Makchan Guangcan Mai
  url:               http://www.comp.hkbu.edu.hk/~csgcmai
  email:             csgcmai@life.hkbu.edu.hk

# Custom vars
version:             1.0.0

gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
